---
# If you want to run 'oc' locally, just use "hosts: localhost" here. Just make sure you can
# run 'oc' with a valid/local kubeconfig.
- hosts: all
  gather_facts: False

  roles:
  - openshift_client_python

  tasks:

  - name: deploy latest changes
    set_fact:
      op_types: "deployments"
      op_routes: "telegraf-newton/openshift.m1.shift.zone"
  - name: Await ingress
    openshift_client_python:
      # Default project scope unless overridden with oc.project
      project: 'newton-idracs'
      # Timeout applies to overall script / all oc interactions must complete
      timeout: 15
      # If you know the script will make changes, you can indicate it as a parameter
      changes: true

      vars:
        some_var_name: 'abc'
        another: 5

      script: |
        print('You can use an arg: {} and {}'.format(oc.ansible.vars['some_var_name'], oc.ansible.vars['another']))

        # "oc.ansible.new_facts" is a dict into which you can store new facts.
        # These facts will be set by ansible when the script exits.
        oc.ansible.new_facts['deployments'] = oc.selector("{{op_types}}").qnames()

        oc.selector('route/"{{op_routes}}"').until_all(1, oc.status.is_route_admitted)

        # An alternate way of reporting a change occurred to the module.
        oc.ansible.changed = True

        oc.selector('route/"{{op_routes}}"').until_all(1, oc.status.is_route_admitted)

    register: result

  - name: Show tracking result (all oc interactions)
    debug:
      msg: "{{result}}"

  - name: Use those facts
    openshift_client_python:
      timeout: 60
      script: |
        with oc.project('newton-idracs'):

          def print_phase(pod_apiobj):
            print('Phase for {} = {}'.format(deployment_apiobj.qname(), deployment_apiobj.model.status.phase))

          oc.selector({{deployments}}).for_each(print_phase)

